force-app/main/default/objects/CUser__c/CUser__c.object-meta.xml
<CustomObject>
    <label>CUser</label>
    <nameField>
        <label>CUser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CUser__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CUser__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CUser__c/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <label>Login</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CUser__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CUser__c/fields/TokenExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>TokenExpiryDate__c</fullName>
    <label>TokenExpiryDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CUser__c/fields/TokenValue__c.field-meta.xml
<CustomField>
    <fullName>TokenValue__c</fullName>
    <label>TokenValue</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CUser__c/fields/ZIP__c.field-meta.xml
<CustomField>
    <fullName>ZIP__c</fullName>
    <label>ZIP</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AuthController.cls
public with sharing class AuthController {
  @AuraEnabled
  public static CUser__c AuthUser(String userRequest) {
    CUser__c user = (CUser__c) JSON.deserialize(userRequest, CUser__c.class);

    ValidateAuth(user);

    CUser__c currentUser = [
      SELECT
        Login__c,
        Email__c,
        Password__c,
        TokenExpiryDate__c,
        TokenValue__c,
        Country__c,
        City__c,
        Street__c,
        ZIP__c,
        Phone__c
      FROM CUser__c
      WHERE Login__c = :user.Login__c
      LIMIT 1
    ];

    CreateToken(currentUser);

    return currentUser;
  }

  @AuraEnabled
  public static CUser__c LogoutUser(String userRequest) {
    CUser__c user = (CUser__c) JSON.deserialize(userRequest, CUser__c.class);

    ClearToken(user);

    return null;
  }

  @AuraEnabled
  public static CUser__c CheckAuthUser() {
    String token = GetToken();

    List<CUser__c> userByTokenList = [
      SELECT
        Login__c,
        Email__c,
        Password__c,
        TokenExpiryDate__c,
        TokenValue__c,
        Country__c,
        City__c,
        Street__c,
        ZIP__c,
        Phone__c
      FROM CUser__c
      WHERE TokenValue__c = :token
      LIMIT 1
    ];
    if (userByTokenList.size() == 0) {
      throw new AuthCheckException('Пожалуйста, авторизуйтесь.');
    }

    CUser__c userByToken = userByTokenList[0];

    if (Datetime.now() > userByToken.TokenExpiryDate__c) {
      ClearToken(userByToken);
      throw new AuthCheckException('Пожалуйста, авторизуйтесь.');
    }

    CreateToken(userByToken);
    return userByToken;
  }

  public static String CreateToken(CUser__c user) {
    user.TokenValue__c = GetToken();
    user.TokenExpiryDate__c = Datetime.now().addHours(1);
    update user;

    return user.TokenValue__c;
  }

  public static void ClearToken(CUser__c user) {
    user.TokenValue__c = null;

    try {
      update user;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  public static String GetToken() {
    return Util.EncryptString(Util.GetUserIPAddress());
  }

  private static void ValidateAuth(CUser__c user) {
    List<CUser__c> userCandidateList = [
      SELECT Password__c
      FROM CUser__c
      WHERE Login__c = :user.Login__c
      LIMIT 1
    ];

    if (userCandidateList.size() == 0) {
      throw new AuraHandledException(
        'Пользователь с таким логином не зарегистрирован.'
      );
    }

    CUser__c userCandidate = userCandidateList[0];

    String pass = Util.EncryptString(user.Password__c);

    if (userCandidate.Password__c != pass) {
      throw new AuraHandledException('Неверный логин или пароль.');
    }
  }
}