force-app/main/default/objects/CategoryToProduct__c/CategoryToProduct__c.object-meta.xml
<CustomObject>
    <label>CategoryToProduct</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ProductCategoryName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CategoryToProduct</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CategoryToProduct__c/fields/ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductCategory__c</fullName>
    <label>ProductCategory</label>
    <referenceTo>ProductCategory__c</referenceTo>
    <relationshipLabel>CategoryToProduct</relationshipLabel>
    <relationshipName>CategoryToProduct</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CategoryToProduct__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <label>Products</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>CategoryToProduct</relationshipLabel>
    <relationshipName>CategoryToProduct</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductCategory__c/ProductCategory__c.object-meta.xml
<CustomObject>
    <label>ProductCategory</label>
    <nameField>
        <label>Product Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductCategories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CategoryToProductSeeder.cls
public class CategoryToProductSeeder {
    
 public static void seed(){
        delete [Select Id From CategoryToProduct__c];
     
        List<Product__c> products = [Select Id From Product__c];
        List<ProductCategory__c> categories = [Select Id From ProductCategory__c];
        List<CategoryToProduct__c> categoryToProductList = new List<CategoryToProduct__c>();
     
        for(Integer i = 0 ; i < products.size(); i++){
            Integer randomCategoryIndex = 0;
            Id categoryId = categories.get(randomCategoryIndex).Id;
            Id productId = products.get(i).Id;
            
            if(categories.size() > 1){
                randomCategoryIndex = (Math.random() * (categories.size() - 1)).intValue();
                categoryId = categories.get(randomCategoryIndex).Id;
                //categories.remove(randomCategoryIndex);
            }
            categoryToProductList.add(new CategoryToProduct__c(
            	Products__c= productId,
                ProductCategory__c =categoryId
            ));
            
        }
        
        upsert categoryToProductList;
    }
}