force-app/main/default/objects/CategoryToProduct__c/CategoryToProduct__c.object-meta.xml
<CustomObject>
    <label>CategoryToProduct</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ProductCategoryName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CategoryToProduct</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CategoryToProduct__c/fields/ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductCategory__c</fullName>
    <label>ProductCategory</label>
    <referenceTo>ProductCategory__c</referenceTo>
    <relationshipLabel>CategoryToProduct</relationshipLabel>
    <relationshipName>CategoryToProduct</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CategoryToProduct__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <label>Products</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>CategoryToProduct</relationshipLabel>
    <relationshipName>CategoryToProduct</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/InStock__c.field-meta.xml
<CustomField>
    <fullName>InStock__c</fullName>
    <label>InStock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/ProductDescription__c.field-meta.xml
<CustomField>
    <fullName>ProductDescription__c</fullName>
    <label>ProductDescription</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/ProductLabel__c.field-meta.xml
<CustomField>
    <fullName>ProductLabel__c</fullName>
    <label>ProductLabel</label>
    <length>127</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/ProductPrice__c.field-meta.xml
<CustomField>
    <fullName>ProductPrice__c</fullName>
    <label>ProductPrice</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ProductCategory__c/ProductCategory__c.object-meta.xml
<CustomObject>
    <label>ProductCategory</label>
    <nameField>
        <label>Product Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductCategories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProductsController.cls
public with sharing class ProductsController {
    private static List<Product__c> filterProducts (List<Product__c> products, string filterParams){    
        Map<string, string> filters = (Map<string, string>)JSON.deserialize(filterParams, Map<string, string>.class);

        if(filters.containsKey('category') && filters.get('category') != null){         
            products = [SELECT 
                        Name,
                        ProductLabel__c,
                        ProductDescription__c,
                        ProductPrice__c,
                        InStock__c FROM Product__c
                        WHERE Id IN (SELECT Products__c FROM CategoryToProduct__c 
                         			WHERE ProductCategory__c = :filters.get('category'))];
        }
        
        if(filters.containsKey('priceMin') && filters.get('priceMin') != null){
            Decimal priceMin = Decimal.ValueOf(filters.get('priceMin'));
            products = [SELECT 
                        Name,
                        ProductLabel__c,
                        ProductDescription__c,
                        ProductPrice__c,
                        InStock__c FROM Product__c 
                        WHERE Id IN :products AND ProductPrice__c >=: priceMin];
        }
        
        if(filters.containsKey('priceMax') && filters.get('priceMax') != null){
            Decimal priceMax = Decimal.ValueOf(filters.get('priceMax'));
            products = [SELECT 
                        Name,
                        ProductLabel__c,
                        ProductDescription__c,
                        ProductPrice__c,
                        InStock__c FROM Product__c 
                        WHERE Id IN :products AND ProductPrice__c <= :priceMax];
        }
        
        return products;
    } 
    
    private static List<Product__c> pagedProducts (List<Product__c> products, string pagerParams){    
        Map<string, string> pager = (Map<string, string>)JSON.deserialize(pagerParams, Map<string, string>.class);
        
        Integer pagerLimit = Integer.ValueOf(pager.get('limit'));
        Integer pagerOffset = Integer.ValueOf(pager.get('offset'));
        Integer productsCount = products.size();
        
        products = [SELECT 
                        Name,
                        ProductLabel__c,
                        ProductDescription__c,
                        ProductPrice__c,
                        InStock__c FROM Product__c 
                        WHERE Id IN :products 
                        LIMIT :pagerLimit OFFSET :pagerOffset];
        
        return products;
    } 
   
    @AuraEnabled
    public static List<Product__c> getProducts(string filterParams, string pagerParams){
        
        List<Product__c> products = [SELECT 
                                     Name,
                                     ProductLabel__c,
                                     ProductDescription__c,
                                     ProductPrice__c,
                                     InStock__c 
                                     FROM Product__c];

        products = filterProducts (products, filterParams);
		products = pagedProducts (products, pagerParams);
        
        return products;
    } 
    
    @AuraEnabled
    public static Integer getProductsCount(string filterParams){
        List<Product__c> products = [SELECT 
                                         Name,
                                         ProductLabel__c,
                                         ProductDescription__c,
                                         ProductPrice__c,
                                         InStock__c 
                                         FROM Product__c];
        
        products = filterProducts (products, filterParams);

        return products.size();
    } 
    
    @AuraEnabled
    public static Product__c getProduct(string productId){
        return [SELECT
                Name,
                ProductLabel__c,
                ProductDescription__c,
                ProductPrice__c,
                InStock__c 
                FROM Product__c
                WHERE Id =: productId];
    } 
    
    @AuraEnabled
    public static List<ContentDocumentLink> getProductAttachments(string productId){
        return [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :productId];
    }
}