force-app/main/default/objects/CategoryToProduct__c/CategoryToProduct__c.object-meta.xml
<CustomObject>
    <label>CategoryToProduct</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ProductCategoryName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CategoryToProduct</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CategoryToProduct__c/fields/ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductCategory__c</fullName>
    <label>ProductCategory</label>
    <referenceTo>ProductCategory__c</referenceTo>
    <relationshipLabel>CategoryToProduct</relationshipLabel>
    <relationshipName>CategoryToProduct</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CategoryToProduct__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <label>Products</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>CategoryToProduct</relationshipLabel>
    <relationshipName>CategoryToProduct</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/InStock__c.field-meta.xml
<CustomField>
    <fullName>InStock__c</fullName>
    <label>InStock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/ProductDescription__c.field-meta.xml
<CustomField>
    <fullName>ProductDescription__c</fullName>
    <label>ProductDescription</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/ProductLabel__c.field-meta.xml
<CustomField>
    <fullName>ProductLabel__c</fullName>
    <label>ProductLabel</label>
    <length>127</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/ProductPrice__c.field-meta.xml
<CustomField>
    <fullName>ProductPrice__c</fullName>
    <label>ProductPrice</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ProductCategory__c/ProductCategory__c.object-meta.xml
<CustomObject>
    <label>ProductCategory</label>
    <nameField>
        <label>Product Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductCategories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductCategory__c/fields/ProductCategoryDescription__c.field-meta.xml
<CustomField>
    <fullName>ProductCategoryDescription__c</fullName>
    <label>ProductCategoryDescription</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProductsControllerTest.cls
@isTest
public class ProductsControllerTest {
    public static Product__c CreateTestProduct(String name, Decimal productPrice,String productLabel, String productDescription,Integer inStock){
        return new Product__c(
            Name = name, 
            ProductPrice__c = productPrice,
            ProductLabel__c = productLabel,
            ProductDescription__c = productDescription,
            InStock__c = inStock
        );
    }

    @isTest
    public static void getProductsTest() {
        Product__C product = CreateTestProduct('name', 1000, 'productLabel', 'productDescription', 10);
        insert product;

        ProductCategory__c category = new ProductCategory__c(Name='Category ', ProductCategoryDescription__c = 'Description ');
        insert category;

        insert new CategoryToProduct__c(Products__c= product.Id, ProductCategory__c =category.Id);

        Map<string, string> filters = new Map<String, String>();
        filters.put('category', category.Id);
        filters.put('priceMin', '100');
        filters.put('priceMax', '200000');

        Map<string, string> pager = new Map<String, String>();
        pager.put('limit', '2');
        pager.put('offset', '0');

        try {
            List<Product__c> products = ProductsController.getProducts(JSON.serialize(filters), JSON.serialize(pager));

            System.assertEquals(true, products.size() == 1);
            
        } catch (Exception e) {
            System.assertEquals(1,0);
        } 
    }

    @isTest
    public static void getProductsCountTest() {
        Product__C product = CreateTestProduct('name', 1000, 'productLabel', 'productDescription', 10);
        insert product;

        ProductCategory__c category = new ProductCategory__c(Name='Category ', ProductCategoryDescription__c = 'Description ');
        insert category;

        insert new CategoryToProduct__c(Products__c= product.Id, ProductCategory__c =category.Id);

        Map<string, string> filters = new Map<String, String>();
        filters.put('category', category.Id);
        filters.put('priceMin', '100');
        filters.put('priceMax', '200000');

        try {
            Integer productsCount = ProductsController.getProductsCount(JSON.serialize(filters));

            System.assertEquals(true, productsCount == 1);
            
        } catch (Exception e) {
            System.assertEquals(1,0);
        } 
    }

    @isTest
    public static void getProductAttachmentsTest() {
        Product__C product = CreateTestProduct('name', 1000, 'productLabel', 'productDescription', 10);
        insert product;

        try {
            List<ContentDocumentLink> attachments = ProductsController.getProductAttachments(product.Id);
            System.assertEquals(true, attachments.size() == 0);
            
        } catch (Exception e) {
            System.assertEquals(1,0);
        } 
    }
}