force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/InStock__c.field-meta.xml
<CustomField>
    <fullName>InStock__c</fullName>
    <label>InStock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/ProductDescription__c.field-meta.xml
<CustomField>
    <fullName>ProductDescription__c</fullName>
    <label>ProductDescription</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/ProductLabel__c.field-meta.xml
<CustomField>
    <fullName>ProductLabel__c</fullName>
    <label>ProductLabel</label>
    <length>127</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/ProductPrice__c.field-meta.xml
<CustomField>
    <fullName>ProductPrice__c</fullName>
    <label>ProductPrice</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ProductSeeder.cls
public class ProductSeeder {
    // public static void seed(){
        
    //     delete [Select Id From Product__c];
        
    //     List<Product__c> products = new List<Product__c>();
        
    //     for(Integer i = 1 ; i < 30; i++){
    //         Integer price = Integer.valueof((Math.random() * 10000)+100);
    //         Integer inStock = Integer.valueof((Math.random() * 100)+10);
            
    //         products.add(new Product__c(
    //             Name='Product '+i, 
    //             ProductPrice__c=price,
    //             ProductLabel__c='Label '+i,
    //             ProductDescription__c='Description '+i,
    //             InStock__c=inStock
    //         ));
    //     }
        
    //     upsert products;
    // }
}