force-app/main/default/objects/ProductCategory__c/ProductCategory__c.object-meta.xml
<CustomObject>
    <label>ProductCategory</label>
    <nameField>
        <label>Product Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductCategories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductCategory__c/fields/ProductCategoryDescription__c.field-meta.xml
<CustomField>
    <fullName>ProductCategoryDescription__c</fullName>
    <label>ProductCategoryDescription</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductCategory__c/fields/ProductCategoryParent__c.field-meta.xml
<CustomField>
    <fullName>ProductCategoryParent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProductCategoryParent</label>
    <referenceTo>ProductCategory__c</referenceTo>
    <relationshipLabel>ProductCategories</relationshipLabel>
    <relationshipName>ProductCategories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductCategoryControllerTest.cls
@isTest
public class ProductCategoryControllerTest {

    @isTest
    public static void getChildCategoriesTest() {
        ProductCategory__c category = new ProductCategory__c(Name='Category ', ProductCategoryDescription__c = 'Description ');
        insert category;
        ProductCategory__c categoryChild = new ProductCategory__c(
            Name='Category ', 
            ProductCategoryDescription__c = 'Description ',
            ProductCategoryParent__c = category.Id);

        insert categoryChild;

        try {
            List<ProductCategory__c>  categories = ProductCategoryController.getChildCategories(category.Id);
            System.assertEquals(true, categories[0].Id == categoryChild.Id);

        } catch (Exception e) {
            System.assertEquals(1, 0);
        }
    }
}