force-app/main/default/objects/ProductCategory__c/ProductCategory__c.object-meta.xml
<CustomObject>
    <label>ProductCategory</label>
    <nameField>
        <label>Product Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductCategories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductCategory__c/fields/ProductCategoryDescription__c.field-meta.xml
<CustomField>
    <fullName>ProductCategoryDescription__c</fullName>
    <label>ProductCategoryDescription</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SearchControllerTest.cls
@isTest
public class SearchControllerTest {

    @isTest
    public static void trySearchTest() {
        ProductCategory__c category = new ProductCategory__c(Name='Category', ProductCategoryDescription__c = 'Description');
        insert category;
        try {
            SearchController.trySearch('Cat');
            System.assertEquals(true, true);
        } catch (Exception e) {
            System.assertEquals(true, false);
        }
    }

    @isTest
    public static void trySearchEmptyTest() {
        try {
            SearchController.trySearch('category');
            System.assertEquals(true, true);
        } catch (Exception e) {
            System.assertEquals(true, false);
        }
    }
}