force-app/main/default/objects/ProductCategory__c/ProductCategory__c.object-meta.xml
<CustomObject>
    <label>ProductCategory</label>
    <nameField>
        <label>Product Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductCategories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductCategory__c/fields/ProductCategoryDescription__c.field-meta.xml
<CustomField>
    <fullName>ProductCategoryDescription__c</fullName>
    <label>ProductCategoryDescription</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductCategory__c/fields/ProductCategoryParent__c.field-meta.xml
<CustomField>
    <fullName>ProductCategoryParent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProductCategoryParent</label>
    <referenceTo>ProductCategory__c</referenceTo>
    <relationshipLabel>ProductCategories</relationshipLabel>
    <relationshipName>ProductCategories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CategoriesSeeder.cls
public class CategoriesSeeder {
    public static void seed(){
        delete [Select Id From ProductCategory__c];
        
        List<ProductCategory__c> categories = new List<ProductCategory__c>();
        
        for(Integer i = 1 ; i < 8; i++){
            
            Integer randomParentIndex = (Math.random() * (categories.size() - 1)).intValue();

            Id parent = null;
            
            if(categories.size()> 2){
                upsert categories.get(randomParentIndex);
                parent = categories.get(randomParentIndex).Id;
            }
             
            categories.add(new ProductCategory__c(
                Name='Category '+i,
                ProductCategoryDescription__c = 'Description '+i,
                ProductCategoryParent__c=parent
            ));
        }
        
        upsert categories;
    }
}